services:
  wordpress:
    image: wordpress:latest
    container_name: wp_container
    ports:
      - "8080:80"  # Exponemos el puerto 80 en el contenedor al 8080 en tu máquina
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html  # Sincroniza el contenido de tu WP localmente
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos para la base de datos
    restart: always

volumes:
  db_data: {}  # Define un volumen persistente para la base de datos
